use SEO ;
drop table if exists LogSession ;
CREATE TABLE IF NOT EXISTS LogSession (
  idSession VARCHAR(50) PRIMARY KEY,

  IP VARCHAR(50),
  UserAgent VARCHAR(200),
  Accept VARCHAR(150),
  Accept_Encoding VARCHAR(100),
  Accept_Language VARCHAR(150),
  Referer VARCHAR(500),

  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;



drop table if exists LogPage ;
CREATE TABLE IF NOT EXISTS LogPage (
  IP VARCHAR(50),
  Page VARCHAR(50),
  Method VARCHAR(10),

  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;

alter table LogPage ADD KEY (IP) ;



