use SEO ;
drop table if exists LogSession ;
CREATE TABLE IF NOT EXISTS LogSession (
  idSession VARCHAR(50) PRIMARY KEY,

  IP VARCHAR(50),
  UserAgent VARCHAR(200),
  Accept VARCHAR(150),
  Accept_Encoding VARCHAR(100),
  Accept_Language VARCHAR(150),
  Referer VARCHAR(500),
  
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;



drop table if exists LogPage ;
CREATE TABLE IF NOT EXISTS LogPage (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,

  idSession VARCHAR(50),
  Page VARCHAR(50),
  Method VARCHAR(10),

  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;


drop table if exists LogUser ;
CREATE TABLE IF NOT EXISTS LogUser (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,

  idSession VARCHAR(50),
  idUser INT(11),

  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
